#!/bin/sh

export ZLIB_LIBS="/../zlib-1.2.11_x64"
export ZLIB_CFLAGS="-L$ZLIB_LIBS -I$ZLIB_LIBS"

export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"
export CFLAGS="$CFLAGS -L$LD_LIBRARY_PATH"

export PATH="$LD_LIBRARY_PATH:$ZLIB_LIBS:$PATH"

./configure --prefix=$(pwd) --host=x86_64-w64-mingw32

echo "Press enter to continue"
read _

make

