#!/bin/sh

export CFLAGS="$CFLAGS -fPIC -static-libgcc -static-libstdc++ -O3"
export CPPFLAGS="$CPPFLAGS -fPIC -static-libgcc -static-libstdc++ -O3"

./configure --prefix=$(pwd) --with-gnu-ld

echo "Press enter to continue"
read _

echo "#!/bin/sh
make">to_make.sh
chmod +x to_make.sh

$SHELL to_make.sh

echo "strip dll"
strip -s src/libmpg123/.libs/*.so*

echo "build .a"
ar r src/libmpg123/.libs/libmpg123.a src/libmpg123/.libs/*.o




