#!/bin/sh

export OPENSSL_LIBS="$(pwd)/../openssl-1.1.1h"
export OPENSSL_CFLAGS="-L$OPENSSL_LIBS -I$OPENSSL_LIBS/include/openssl"

libev_PREFIX=""

export CFLAGS="-U__STRICT_ANSI__ -I$libev_PREFIX/include -L$libev_PREFIX/lib"
export CXXFLAGS="$CFLAGS"

export ZLIB_LIBS="$(pwd)/../zlib-1.2.11"
export ZLIB_CFLAGS="-L$ZLIB_LIBS -I$ZLIB_LIBS"

export LD_LIBRARY_PATH="/usr/lib/i386-linux-gnu"
export CFLAGS="$CFLAGS -L$LD_LIBRARY_PATH"

export PATH="$LD_LIBRARY_PATH:$ZLIB_LIBS:$OPENSSL_LIBS:$PATH"

./configure --prefix=$(pwd) --host=i686-w64-mingw32

echo "Press enter to continue"
read _

make

