#!/bin/sh

export CFLAGS="$CFLAGS -fPIC -static-libgcc -static-libstdc++ -O3"
export CPPFLAGS="$CPPFLAGS -fPIC -static-libgcc -static-libstdc++ -O3"

./configure --prefix=$(pwd) --with-gnu-ld

echo "Press enter to continue"
read _

echo "#!/bin/sh
make">to_make.sh
chmod +x to_make.sh

$SHELL to_make.sh

echo "strip dll"
strip -s lib/.libs/*.so*

echo "build .a"
ar r lib/.libs/libportaudio.a src/*/.libs/*.o src/*/*/.libs/*.o
